POST http://localhost:3333/events
Content-Type: application/json

{
  "title":123,
  "details":null,
  "maximumAttendees":1
}


###

POST http://localhost:3333/events/73454bef-f9cf-4a08-ae5e-7ab8ffbff16b/attendees
Content-Type: application/json

{
  "name":"Harry Lynch",
  "email":"leszicob@neoz.kn"
}

###

GET http://localhost:3333/events/f1097d24-8af0-4b8d-9d0d-ef6e7bbb4011

###

GET http://localhost:3333/attendees/9/badge

###

GET http://localhost:3333/attendees/7/check-in
###

GET http://localhost:3333/events/025093a1-8a2e-4c23-8a18-a25dd8ea2b65/attendees?query=amelia